version: '3'

services:
  web:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py crontab add && python3 manage.py runserver 0.0.0.0:8000 --insecure"
    ports:
      - "1010:8000"