# Generated by Django 4.1.1 on 2022-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
