# Generated by Django 4.1.1 on 2022-11-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_session_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.session')),
            ],
        ),
    ]
