# Generated by Django 4.1.1 on 2022-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_rename_file_name_session_old_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='new_file_name',
        ),
        migrations.AddField(
            model_name='session',
            name='translatedText',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
